AllCops:
  Exclude:
    - 'appveyor.yml'
    - 'Vagrantfile'
    - 'scripts/**/*'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

ModuleLength:
  Max: 250

ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
