AllCops:
  Exclude:
    - 'appveyor.yml'
    - 'Vagrantfile'
    - 'scripts/**/*'
    - 'vendor/**/*'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

ModuleLength:
  Max: 250

Naming/HeredocDelimiterNaming:
  Enabled: false

ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
