AllCops:
  Exclude:
    - 'appveyor.yml'
    - 'scripts/**/*'
    - 'lib/winrm/winrm_service.rb'
    - 'lib/winrm/http/transport.rb'

Style/Encoding:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
  