## Kerberos
#auth_type: plaintest
#endpoint: "http://<yourserver>:5985/wsman"
#options:
#  realm: "your.realm"

## Plain Text
auth_type: plaintext
endpoint: "http://localhost:55985/wsman"
options:
  user: vagrant
  pass: vagrant